version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
  db:
    image: postgres:17-alpine3.21
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  checkout:
    build:
      context: ./checkout
      args:
        - MAVEN_OPTS=-Dmaven.test.skip=true
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/checkout
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=rabbitmq
      - spring.rabbitmq.password=rabbitmq
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8081:8080"
  product:
    build: 
      context: ./product
      args:
        - MAVEN_OPTS=-Dmaven.test.skip=true
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/product
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=rabbitmq
      - spring.rabbitmq.password=rabbitmq
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8082:8080"
  wallet:
    build:
      context: ./wallet
      args:
        - MAVEN_OPTS=-Dmaven.test.skip=true
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/wallet
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=rabbitmq
      - spring.rabbitmq.password=rabbitmq
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8083:8080"
volumes:
  db-data: