version: "3"
services:
  db:
    image: postgres:17-alpine3.21
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
  checkout:
    build: ./checkout
    environment:
      - spring.r2dbc.url=r2dbc:postgresql://db:5432/checkout
      - spring.r2dbc.username=postgres
      - spring.r2dbc.password=postgres
  product:
    build: ./product
    environment:
      - spring.r2dbc.url=r2dbc:postgresql://db:5432/product
      - spring.r2dbc.username=postgres
      - spring.r2dbc.password=postgres
  wallet:
    build: ./wallet
    environment:
      - spring.r2dbc.url=r2dbc:postgresql://db:5432/wallet
      - spring.r2dbc.username=postgres
      - spring.r2dbc.password=postgres
volumes:
  db-data: