spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: postgres
  application:
    name: product
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: none
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
