logging:
  level:
    br.ufrn.imd.markethub: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: postgres
    password: postgres
  application:
    name: wallet
  rabbitmq:
    host: localhost
    port: 5672
    username: username
    password: password
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    properties.hibernate.format_sql: false
    hibernate.ddl-auto: none
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
