name: CI Build

on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify Checkout Service
        run: ./mvnw verify
        working-directory: ./checkout

      - name: Verify Product Service
        run: ./mvnw verify
        working-directory: ./product

      - name: Verify Wallet Service
        run: ./mvnw verify
        working-directory: ./wallet

      - run: mkdir staging && cp checkout/target/*.jar staging && cp product/target/*.jar staging && cp wallet/target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging