name: CI Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Verify Checkout Service
        run: ./mvnw verify
        working-directory: ./checkout

      - name: Verify Product Service
        run: ./mvnw verify
        working-directory: ./product

      - name: Verify Wallet Service
        run: ./mvnw verify
        working-directory: ./wallet

      - name: Upload Checkout JAR
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: checkout-jar
          path: checkout/target/*.jar

      - name: Upload Product JAR
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: product-jar
          path: product/target/*.jar

      - name: Upload Wallet JAR
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: wallet-jar
          path: wallet/target/*.jar